# 외부 DB 설정시 아래의 주석을 활성화 시킨 후 관련 DB 설정 정보를 입력한다.
spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  security:
    user:
      name: user
      password: pwd

spring.h2.console:
  enabled: true
  path: /h2-console


#security:
#  oauth2:
#    client:
#      client-id: client
#      client-secret: secret
#      scope:
#        - read
#        - write
#    authorization:
#      token-key-access: isAuthenticated()
#    resource:
#      jwt:
#        key-value: jwt_key_test


logging.level:
  org.springframework:
    security: debug
    boot: debug
